### ISSUE TITLE
Progress on your project all that jazz

### ISSUE THREAD

**Issue by yungyuc** [S413/AllThatJazz#1]
There seem to be no progress on the code for your project all that jazz.  Do you need any help?

**Comment by S413** [comment]
I did start on it, but I haven't pushed.
On the other hand, I am indeed behind schedule.
When I began I was distracted by reading mathematical formulas as input in Cpp.

**Comment by yungyuc** [comment]
When you push to the repository and want my review, open an issue in your repository and tag me.
